<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.22000.0</SupportedOSPlatformVersion>
    <RootNamespace>ExcalidrawZ.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.WindowsAppSDK" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExcalidrawZ.Canvas\ExcalidrawZ.Canvas.csproj" />
    <ProjectReference Include="..\ExcalidrawZ.Domain\ExcalidrawZ.Domain.csproj" />
    <ProjectReference Include="..\ExcalidrawZ.Storage\ExcalidrawZ.Storage.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\Canvas\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>CanvasContent\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <TargetPath>CanvasContent\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </Content>
  </ItemGroup>
</Project>
