//
//  Generated by refactoring AdjustElementsTool.swift.
//

import Foundation

extension AdjustElementsMiddleware {
    func applyWrapOp(
        _ op: WrapOp,
        elements: inout [ExcalidrawElement],
        createdElementIds: inout [String]
    ) throws {
        let result = try hydrateWrapOp(op, existingElements: elements)
        elements.append(contentsOf: result.elements)
        createdElementIds.append(contentsOf: result.elements.map(\.id))
    }

    func hydrateWrapOp(_ op: WrapOp, existingElements: [ExcalidrawElement]) throws -> WrapOpResult {
        let targetIDs = uniqueIDs(op.targetIds)
        guard !targetIDs.isEmpty else {
            throw AdjustmentError(message: "wrap requires at least one targetId.")
        }

        let targetIndexes = try targetIDs.map { try indexOfElement($0, in: existingElements) }
        let targets = targetIndexes.map { existingElements[$0] }
        if let deletedID = targets.first(where: { $0.isDeleted })?.id {
            throw AdjustmentError(message: "Cannot wrap deleted element \(deletedID).")
        }

        let shape = try parseWrapType(op.shape)
        let style = hydratedStylePreset(op.stylePreset).merged(with: op.style)
        let bounds = unionBounds(of: targets)
        let padding = max(0, op.padding ?? 24)
        let labelText = op.label?.trimmingCharacters(in: .whitespacesAndNewlines)
        let hasInsideLabel = labelText?.isEmpty == false && op.labelPosition != "above"
        let labelFontSize = style.fontSize ?? 18
        let labelReservedTop = hasInsideLabel
            ? defaultTextHeight(text: labelText ?? "", fontSize: labelFontSize) + 12
            : 0
        let wrapperX = bounds.minX - padding
        let wrapperY = bounds.minY - padding - labelReservedTop
        let wrapperWidth = max(1, bounds.maxX - bounds.minX + padding * 2)
        let wrapperHeight = max(1, bounds.maxY - bounds.minY + padding * 2 + labelReservedTop)
        let now = nowMillis()

        let wrapper = ExcalidrawGenericElement(
            type: shape,
            id: ExcalidrawNanoID.make(),
            x: wrapperX,
            y: wrapperY,
            strokeColor: style.strokeColor ?? "#1e1e1e",
            backgroundColor: style.backgroundColor ?? "transparent",
            fillStyle: .solid,
            strokeWidth: style.strokeWidth ?? 2,
            strokeStyle: .solid,
            roundness: shape == .rectangle ? ExcalidrawRoundness(type: .adaptiveRadius, value: nil) : nil,
            roughness: style.roughness ?? 1,
            opacity: style.opacity ?? 100,
            width: wrapperWidth,
            height: wrapperHeight,
            angle: 0,
            seed: randomSeed(),
            version: 1,
            versionNonce: randomNonce(),
            index: nil,
            isDeleted: false,
            groupIds: [],
            frameId: nil,
            boundElements: [],
            updated: now,
            link: nil,
            locked: false,
            customData: nil,
            strokeSharpness: nil
        )

        var createdElements: [ExcalidrawElement] = [.generic(wrapper)]
        if let label = hydratedWrapLabel(
            op.label,
            labelPosition: op.labelPosition,
            wrapperX: wrapperX,
            wrapperY: wrapperY,
            style: style,
            updated: now
        ) {
            createdElements.append(.text(label))
        }

        return WrapOpResult(
            elements: createdElements
        )
    }


    func hydratedWrapLabel(
        _ rawLabel: String?,
        labelPosition: String?,
        wrapperX: Double,
        wrapperY: Double,
        style: StylePatch,
        updated: Double
    ) -> ExcalidrawTextElement? {
        guard let text = rawLabel?.trimmingCharacters(in: .whitespacesAndNewlines),
              !text.isEmpty else {
            return nil
        }

        let fontSize = style.fontSize ?? 18
        let width = defaultTextWidth(text: text, fontSize: fontSize)
        let height = defaultTextHeight(text: text, fontSize: fontSize)
        let labelX = wrapperX + 12
        let labelY: Double
        switch labelPosition {
            case "above":
                labelY = wrapperY - height - 4
            default:
                labelY = wrapperY + 8
        }

        return ExcalidrawTextElement(
            type: .text,
            id: ExcalidrawNanoID.make(),
            x: labelX,
            y: labelY,
            strokeColor: style.strokeColor ?? "#1e1e1e",
            backgroundColor: "transparent",
            fillStyle: .solid,
            strokeWidth: style.strokeWidth ?? 1,
            strokeStyle: .solid,
            roundness: nil,
            roughness: style.roughness ?? 1,
            opacity: style.opacity ?? 100,
            width: width,
            height: height,
            angle: 0,
            seed: randomSeed(),
            version: 1,
            versionNonce: randomNonce(),
            index: nil,
            isDeleted: false,
            groupIds: [],
            frameId: nil,
            boundElements: [],
            updated: updated,
            link: nil,
            locked: false,
            customData: nil,
            fontSize: fontSize,
            fontFamily: .int(Int(style.fontFamily ?? 5)),
            text: text,
            textAlign: parseTextAlign(style.textAlign) ?? .left,
            verticalAlign: parseVerticalAlign(style.verticalAlign) ?? .top,
            containerId: nil,
            originalText: text,
            autoResize: true,
            lineHeight: 1.25
        )
    }

}
